version: '3.8'

services:
  # H2 Database service
  h2-database:
    image: oscarfonts/h2:latest
    container_name: tasks-h2-db
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2_data:/opt/h2-data
    environment:
      - H2_OPTIONS=-web -webAllowOthers -tcp -tcpAllowOthers -baseDir /opt/h2-data
    restart: unless-stopped

  # Backend service (Spring Boot with Kotlin)
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: tasks-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:9092/./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
    depends_on:
      - h2-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (Angular SSR)
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: tasks-frontend
    ports:
      - "4200:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy

volumes:
  h2_data:
