version: '3.8'

services:
  # Backend service (Spring Boot with Kotlin)
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: tasks-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (Angular SSR)
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: tasks-frontend
    ports:
      - "4200:4000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
